name: Test sudoku
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Verify
        run: mvn -B verify -f sudoku/pom.xml
